### ISSUE TITLE
looking for min and max date date lock

### ISSUE THREAD

**Issue by ShankzPatil** [g1eb/angular-datetime-range#12]
looking for min and max date date lock

**Comment by g1eb** [comment]
Hi there! Thanks for reaching out, I've added min and max date attributes in the latest release :)

They are optional, but when set will prevent users from selecting dates outside the boundaries, see [readme](https://github.com/g1eb/angular-datetime-range#attributes) for how to use them.

v0.2.15

**Comment by ShankzPatil** [comment]
Thnx for support 👍
