### ISSUE TITLE
Support angular date filter

### ISSUE THREAD

**Issue by ShankzPatil** [g1eb/angular-datetime-range#23]
hi,

please Support Moment Locales.

**Comment by ShankzPatil** [comment]
Please support angular locale by default.

**Comment by g1eb** [comment]
Hi, apologies for the late reply, could you please elaborate on this?

What functionality is missing and what would you like to see supported? Thanks!

**Comment by ShankzPatil** [comment]
I am looking for translation of words month name week names like angular locale does.
Using date time format.

Angular-translate

**Comment by g1eb** [comment]
Typically, you would have already setup moment js locale in your app.

Please refer to the moment.js docs: https://momentjs.com/downloads/moment-with-locales.js

**Comment by ShankzPatil** [comment]
sorry, for the incomplete information,
i dont want moment locale format, i want to use default angular date filter.
so ther will be change in your html.
