### ISSUE TITLE
Calendar | Month-Year navigation

### ISSUE THREAD

**Issue by IbrahimHd** [g1eb/angular-datetime-range#4]
Hi Gleb,

The support of **scroll** over the time elements is so useful!
Could you please consider supporting scroll for the **Month** as well? This will be useful if the date needs to be moved for long period of time, something like (1-3-2015 to 30-3-2016). It helps avoiding clicking too many times.
It's also worth to mention that scrolling over the month is expected to moves through the calendar (months) but not looping through the (12 months).

Hopeful this can be added on the road-map of improvements.

thanks a lot!

**Comment by g1eb** [comment]
Good suggestion, I've added it to the latest release(v0.2.7) 👍 

With respect to looping, scroll behavior is exactly the same as clicking on the left/right arrows which is consistent with scroll behavior with hours/minutes/seconds.

**Comment by IbrahimHd** [comment]
Thanks Gleb for implementing scrolling over Month.

During scrolling it's difficult to know "where I'm" especially if the date needs to move to another year.
Do you see that displaying the year next to month like **MONTH YYYY** helps overcoming that issue?
(year can be shown only if it's not the current one, or simply always visible)

Thanks!

**Comment by g1eb** [comment]
Good idea! :) I've added that to the latest version (v0.2.9)

**Comment by IbrahimHd** [comment]
thanks 👍
