### ISSUE TITLE
Scroll disorder with some mouses

### ISSUE THREAD

**Issue by IbrahimHd** [g1eb/angular-datetime-range#8]
Hi Gleb,

The scroll feature works fine with some mouses but does not with other ones.
For instance, it works perfect with a Microsoft mouse but with "E-Blue" one it **moves 2-steps with a single scroll**.

Do you have any clue why such thing happens?

**Comment by g1eb** [comment]
That's true, from what I've noticed I can say that using a mouse with a _clicking_ scroll wheel one can make selections much more accurate than using a mouse or touchpad with _smooth_ scroll.

As of yet I'm afraid there is no good solution, it seems hard to test this because of great diversity in mouse/touchpad hardware.

**Comment by g1eb** [comment]
I have an idea on how to test this.

1. Check if binding to different events changes behavior on different hardware (for example ```mousewheel``` event is deprecated according to [MDN](https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel#wikiArticle))

2. Set a threshold for deltaY, that is to say, jump only after scrolling a set distance (it's too sensitive on some devices right now)

The idea is to make this behavior consistent across different mouse/touchpad hardware.

**Comment by IbrahimHd** [comment]
Hi Gleb,
I checked using scrolling with the same mouse on the time-picker of **[ui-bootstrap](https://angular-ui.github.io/bootstrap/#/timepicker)** (Bootstrap in Angular-way) and it functions fine (each tic goes one step for increment/decrement)
I think code needs to be "tweaked" somehow to overcome this issue. (it will be helpful if you can take a look on their code)
Thnx

**Comment by g1eb** [comment]
Good idea :) Essentially, they are doing exactly the same thing ([see code](https://github.com/angular-ui/bootstrap/blob/master/src/timepicker/timepicker.js#L213)) but I noticed they don't bind to the DOMMouseScroll event so I removed that (which is deprecated anyway).

Could you test updated scroll behavior with your mouse please?

v0.2.12

**Comment by IbrahimHd** [comment]
Works as expected!
Thnx
